config/routes.rb
Rails.application.routes.draw do

  root 'login#new'
  get 'login' => 'login#new'
  post 'login' => 'login#create'
  get 'logout' => 'login#destroy'
  resources :students, only: [:index,:new, :create,:edit,:update]

  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :teachers
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :subjects, :through => :subjectstudent
  has_many :subjectstudent, dependent: :destroy
  validates :name, :presence => true
  attr_accessor :sub_id, :mark
  after_create :subject
  after_save :cal_total, :ranking

  def cal_total
     total = 0
     self.subjectstudent.each do |sub_mark|
      total = total + sub_mark.marks
     end
     self.update_column(:total,total)
  end

  def ranking
        rank, i = 1, 0
        student=Student.order(total: :desc)
        student = student.map{ |c| [c.id,c.total] }.to_h
        student_mark = []
        student.each_value{|v|     student_mark << v}
        student.map { |k,x|
          i += 1
          if x != student_mark[i-2]
            rank = i
          else
            rank
          end
          q=Student.find k
          q.update_column(:rank,rank)
        }
  end

  def subject
    h = {}
    sub_id.zip(mark) { |a,b| h[a.to_sym] = b }
    h.each do |k,v|
      Subjectstudent.create(student_id: self.id, subject_id: k, marks: v) if v.present?
    end
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher, :optional => true
  has_many :students, :through => :subjectstudent
  has_many :subjectstudent, dependent: :destroy

end

app/models/subjectstudent.rb
class Subjectstudent < ApplicationRecord
  belongs_to :subject
  belongs_to :student

  def self.subject(id)
    subject = Subject.find id
    subject = subject.sub_name
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :school
  has_one :subject

  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i
  #before_create { generate_token(:auth_token) }
  before_save :encrypt_password
  attr_accessor :password
  validates :firstname, :presence => true
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    teacher = find_by_email(email)
    if teacher && teacher.password_hash == BCrypt::Engine.hash_secret(password, teacher.password_salt)
      teacher
    else
      nil
    end
  end


  # def generate_token(column)
  #   begin
  #     self[column] = SecureRandom.urlsafe_base64
  #   end while User.exists?(column => self[column])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    if session[:teacher_id]
      @current_user ||= Teacher.find(session[:teacher_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new

  end
  def create
    teacher = Teacher.authenticate(params[:email], params[:password])
    if teacher && teacher.active == true
      session[:teacher_id] = teacher.id
      redirect_to teachers_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:teacher_id] = nil
    redirect_to login_url, notice: "Logged out!"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  #after_action :student_subject, only: [:create]

  # GET /teachers
  # GET /teachers.json
  def index
     @students= Student.all
     #@subjects = Student.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end
  #
  # # GET /teachers/new
  def new
    @student = Student.new
    @subjects = Subject.all
  end
  #
  # # GET /teachers/1/edit
  def edit
    @subjects = Subject.all
  end
  #
  # # POST /teachers
  # # POST /teachers.json
  def create
    @params = params
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        #Student.subject(@student)
        format.html { redirect_to action: "index" }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # # PATCH/PUT /teachers/1
  # # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to action: "index" }
        format.json { render :index }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # # DELETE /teachers/1
  # # DELETE /teachers/1.json
  # def destroy
  #   @teacher.destroy
  #   respond_to do |format|
  #     format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  #
  private
  # def student_subject
  #   h = {}
  #   @params["id"].zip(@params["mark"]) { |a,b| h[a.to_sym] = b }
  #   h.each do |k,v|
  #     Subjectstudent.create(student_id: @student.id, subject_id: k, marks: v)
  #   end
  # end
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :standard, :rank, sub_id: [], mark: [])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  after_action  :teacher_subject, only: [:update, :create]

  # GET /teachers
  # GET /teachers.json
  def index
    teacher = @current_user

    if teacher.role == 'admin'
    @teachers = Teacher.all
    else
      redirect_to :controller => 'students', :action => 'index'
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @params = params
    @teacher = Teacher.new(teacher_params)
    @teacher.school_id = School.first.id

    respond_to do |format|
      if @teacher.save
        #Teacher.teacher_subject(@teacher,params["subject"])
        format.html { redirect_to action: "index" }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to action: "index" }
        format.json { render :index }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

  def teacher_subject
    if @params["teacher"]["subject_id"].present?
      subject = Subject.find  @params["teacher"]["subject_id"]
      subject.teacher_id = @teacher.id
      subject.save
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:firstname, :lastname, :email,  :password, :role, :school_id, subject: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RankingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="logout"><%= link_to "Log Out", logout_path %></p>
    <%= yield %>
  </body>
</html>

app/views/login/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/login/destroy.html.erb
<h1>Login#destroy</h1>
<p>Find me in app/views/login/destroy.html.erb</p>

app/views/login/new.html.erb
<p id=”alert”><%= alert %></p>
<h1>Login</h1>
<%= form_tag login_url do |form| %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :standard %>
    <%= form.text_field :standard %>
  </div>

  <% @subjects.each do |subject| %>
    <%= form.label subject.sub_name %>
    <%= hidden_field_tag "student[sub_id][]", subject.id %>
    <%= form.text_field :mark, name: "student[mark][]"%>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= form_with(model: @student, local: true) do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :standard %>
    <%= form.text_field :standard %>
  </div>

  <% @student.subjectstudent.each do |subject| %>
    <%= form.label subject.subject.sub_name %>
    <%= hidden_field_tag "student[sub_id][]", subject.subject_id %>
    <%= form.text_field :mark, name: "student[mark][]", value: subject.marks%>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Students</h1>

<table>
  <thead>
  <tr>
      <th>Name</th>
      <th>Standard</th>
      <th>English</th>
      <th>Tamil</th>
      <th>Total</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.standard %></td>
        <% student.subjectstudent.each do |subject| %>
          <td><%= subject.marks%></td>
        <%end %>
        <% if student.subjectstudent.count == 1 %>
        <td></td>
          <%end %>
        <td><%= student.total %></td>
        <td><%= student.rank %></td>
        <td class="edit"><%= link_to 'Edit', edit_student_path(student) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.tname %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @student.standard %>
</p>

<p>
  <strong>School:</strong>
  <%= @teacher.school_id %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <% if !teacher.persisted? %>
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
    <%end %>

  <div class="field">
    <%= form.label :subject %>
    <%=form.select("subject_id", Subject.all.collect {|p| [ p.sub_name, p.id ] }, { include_blank: false }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Subject</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.firstname %></td>
        <td><%= teacher.role %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.subject.sub_name  if !teacher.subject.nil?%></td>
<!--        <td><%##= link_to 'Show', teacher %></td>-->
        <td class="edit"><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td class="edit"><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.firstname %>
</p>

<p>
  <strong>Role:</strong>
  <%= @teacher.role %>
</p>

<p>
  <strong>School:</strong>
  <%= @teacher.school_id %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>